OPERATORS = {
    'is_null': lambda f: f == None,
    'is_not_null': lambda f: f != None,
    'desc': lambda f: f.desc,
    'asc': lambda f: f.asc,
    '==': lambda f, a: f == a,
    'eq': lambda f, a: f == a,
    'equals': lambda f, a: f == a,
    'equal_to': lambda f, a: f == a,
    '!=': lambda f, a: f != a,
    'ne': lambda f, a: f != a,
    'neq': lambda f, a: f != a,
    'not_equal_to': lambda f, a: f != a,
    'does_not_equal': lambda f, a: f != a,
    '>': lambda f, a: f > a,
    'gt': lambda f, a: f > a,
    '<': lambda f, a: f < a,
    'lt': lambda f, a: f < a,
    '>=': lambda f, a: f >= a,
    'ge': lambda f, a: f >= a,
    'gte': lambda f, a: f >= a,
    'geq': lambda f, a: f >= a,
    '<=': lambda f, a: f <= a,
    'le': lambda f, a: f <= a,
    'lte': lambda f, a: f <= a,
    'leq': lambda f, a: f <= a,
    'ilike': lambda f, a: f.ilike(a),
    'like': lambda f, a: f.like(a),
    'in': lambda f, a: f.in_(a),
    'not_in': lambda f, a: ~f.in_(a),
    '$isnull': lambda f: f == None,
    '$notnull': lambda f: f != None,
    '$eq': lambda f, a: f == a,
    '$equal': lambda f, a: f == a,
    '$ne': lambda f, a: f != a,
    '$neq': lambda f, a: f != a,
    '$gt': lambda f, a: f > a,
    '$lt': lambda f, a: f < a,
    '$ge': lambda f, a: f >= a,
    '$gte': lambda f, a: f >= a,
    '$geq': lambda f, a: f >= a,
    '$le': lambda f, a: f <= a,
    '$lte': lambda f, a: f <= a,
    '$leq': lambda f, a: f <= a,
    '$likeI': lambda f, a: f.ilike('%' + a + '%'),
    '$like': lambda f, a: f.like('%' + a + '%'),
    '$contains': lambda f, a: f.like('%' + a + '%'),
    '$startsWith': lambda f, a: f.like(a + '%'),
    '$starts_with': lambda f, a: f.like(a + '%'),
    '$in': lambda f, a: f.in_(a),
    '$nin': lambda f, a: ~f.in_(a),
}

READONLY_METHODS = frozenset(('GET', ))

LINKTEMPLATE = '<{0}?page={1}&results_per_page={2}>; rel="{3}"'

APINAME_FORMAT = "{0}api"
BLUEPRINTNAME_FORMAT = "{0}{1}"